version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: cimg/base:edge
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run: |
          echo "=========================="
          docker compose version
          echo $CIRCLE_PULL_REQUEST
