version: 2.1

orbs:
  win: circleci/windows@5.0

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    executor:
      name: win/server-2022
      version: "2023.03.1"
    steps:
      - checkout
      - run: |
          echo "hi"
          ssh -V
