version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run: |
          sudo snap install gotham
          gotham version
