version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run: ls -lah /bin/sh
      - run: apk add bash
      - run: ls -lah /bin/sh
      - run: ln -s /bin/sh bash
      - run: which bash
      - run: echo "CHICKEN=you" >> $BASH_ENV
      - run: echo $CHICKEN
