version: 2.1

orbs:
  hugo: circleci/hugo@dev:ricardo-test

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt-get update && apt-get install -y curl
      - hugo/install:
          version: "0.69"
      - run: hugo version
