version: 2
jobs:
  build:
    machine: true
    working_directory: ~/project
    environment:
      - DEBIAN_FRONTEND: "noninteractive"
    steps:
      - checkout
      - run:
          name: "Install Vagrant and spit up VM."
          command: |
            uname -a
            wget https://releases.hashicorp.com/vagrant/1.9.5/vagrant_1.9.5_x86_64.deb
            sudo apt-get update -y && sudo apt-get upgrade -y
            sudo apt-get install -y virtualbox-dkms virtualbox dkms linux-headers-4.4.0-53-generic linux-headers-generic
            sudo dpkg -i vagrant_1.9.5_x86_64.deb
            vagrant --version
            free -m
            vagrant up
            free -m
            vagrant status
