version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      image: ubuntu-2004:canary
      #image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: |
          go version
          ls -lah /usr/local/bin/circleci-install
