version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run: |
          ldd --version
          sudo apt-get update && sudo apt-get upgrade -y
          ldd --version
