version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      image: ubuntu-1604:202010-01
    steps:
      - checkout
      - run: |
          docker --version
          docker-compose --version
          cat /etc/os-release
          uname -a
          aws --version
          gradle --version
          heroku --version
          mvn --version
          java -version || java --version
          sbt --version
          lein --version
