version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      image: ubuntu-2004:2022.07.1
    resource_class: arm.medium
    steps:
      - checkout
      - run: dpkg --print-architecture
      - run: |
          cat /etc/apt/sources.list
          echo $JAVA_HOME
          which javac
          which java
          go version
          jq --version
          docker --version
          #snapcraft --version
          node --version
          java -version
          nvm --version
          nvm install node
          node --version
          cat /etc/os-release
          sudo apt-get update
