version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      image: windows-server-2019-vs2019:stable
      resource_class: windows.medium
    steps:
      - checkout
      - run: |
          node --version
          go version
          npm list
          npx eslint --version
          npm list
          choco install visualstudio2019community -y --params="--allWorkloads --includeRecommended --no-update --includeOptional --passive --noUpdateInstaller --locale en-US" --version="16.3.6.0" --no-progress
