version: 2.1

orbs:
  n: circleci/node@dev:93a8596

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - run: gcloud version
      - run: node --version
      - n/install
      - run: node --version
