version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: circleci/circleci-cli:latest
    steps:
      - checkout
      - run:
          name: "Do all the things!!"
          command: |
            echo "Hi"
