version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run: |
          python --version
          eval "$(pyenv init -)"
          pyenv --version
          pyenv install -v 3.7.2
          pyenv global 3.7.2
          python --version
          python3 --version
