version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: cimg/node:16.0
      - image: circleci/postgres:13.2
    steps:
      - checkout
      - run:
          name: "Do all the things!"
          command: |
            psql -h localhost -p 5432 -U root -c "\l"
