version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      resource_class: gpu.nvidia.small
      image: ubuntu-1604-cuda-10.1:201909-23
    steps:
      - checkout
      - run:
          name: "Test is cuda is available.."
          command: nvidia-smi
      - run: docker version
      - run: dpkg -l nvidia-container-toolkit
      - run: nvcc --version
