version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          cd /opt/circleci/.pyenv/plugins/python-build/../.. && git pull && cd -
          pyenv install 3.7.0
          pyenv global 3.7.0
