version: 2
jobs:
  build:
    docker:
      - image: naftulikay/circleci-lambda-rust:latest
    environment:
      PATH: /home/circleci/.cargo/bin:/home/circleci/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    steps:
      - checkout
      - run:
          name: "Test Environment Values"
          command: echo $TEST_VAR; echo $TEST_VAR2; echo $TEST_VAR3
