version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: cimg/base:current
      - image: cimg/postgres:15.0
    steps:
      - run: git --version
      - checkout
