version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3
    steps:
      - run:
          name: "Set 45 second Build Time Limit"
          command: sleep 45; touch .fail-build; exit 1
          background: true
      - checkout
      - run: |
          sleep 20
          echo "Break 1"
          sleep 20
          echo "Break 2"
          #sleep 20
          #echo "Break 3"
          #sleep 20
          #echo "Break 4"
      - run:
          name: "This should never run."
          command: echo "Damn, I ran."
      - run:
          name: "Enforce Build Time Limit"
          command: if [ -f .fail-build ]; then echo "Build ran too long."; exit 1; fi
          when: always
