version: 2.1

orbs:
  ruby: circleci/ruby@dev:install-fix

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/base:2019.11
    steps:
      - ruby/install:
          version: 2.5.3
      - run: |
          ruby --version
          which ruby
          rvm --version
