version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-27-node8-alpha
    steps:
      - checkout
      - run:
          name: "Check Envar"
          command: |
            bundle
