version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: ~/project
    environment:
      - DEBIAN_FRONTEND: "noninteractive"
    steps:
      - checkout
      - run:
          name: "Install Vagrant and spit up VM."
          command: |
            psql --version
