version: 2.1

orbs:
  jq: circleci/jq@2.0.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt-get update && apt-get install -y curl
      - jq/install
      - run: jq help
