version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/base:stable
      - image: circleci/postgres:9.6.17
        environment:
          POSTGRES_USER: turkey
          #POSTGRES_PASSWORD: chicken
    steps:
      - checkout
      - run: |
          sudo apt-get update && sudo apt-get install -y postgresql-client
      - run:
          name: "Wait For DB to be Ready"
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: "Verify PostgreSQL Version"
          command: PAGER=cat psql -d circle_test -U turkey -h 127.0.0.1 -c 'SELECT version();'
      - run:
          name: "Try Creating a New Database"
          command: |
            PAGER=cat psql -d circle_test -U turkey -h 127.0.0.1 -c 'CREATE DATABASE my_test_database;'
            PAGER=cat psql -d circle_test -U turkey -h 127.0.0.1 -c '\list'
