version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: felicianotech/test:dev-node
    steps:
      - checkout
      - run: echo $TESTOR
      - run: node --version
      - run: nvm install 16.0.0
      - run: node --version
      - run: nvm use 16.0.0
      - run: node --version
      - setup_remote_docker:
          version: 20.10.14
