version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.8
      - run:
          name: "Do all the things!"
          command: |
            docker build -t my-org/my-image .
            docker push my-org/my-image
