version: 2.1

orbs:
  gcp: circleci/gcp-cli@1.8

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      image: ubuntu-1604:202010-01
    steps:
      - run: gcloud version
      - gcp/install
      - gcp/initialize
      - run: gcloud version
