version: 2
jobs:
  build:
    docker:
      - image: node:8.1.4-alpine
    steps:
      - checkout
      - run:
          name: "Check Docker"
          command: |
            if [[ ! $CIRCLE_JOB ]]; then
              echo "CIRCLE_JOB is not set"
            else
              echo "CIRCLE_JOB is set"
              echo "And the value is: " $CIRCLE_JOB
            fi
