version: 2.1

orbs:
  ruby: circleci/ruby@dev:0.2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/base:2019.11
    steps:
      - ruby/install:
          version: 2.7.0-preview3
      - run: |
          ruby --version
