version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Check Docker"
          command: docker version
      - setup_remote_docker
      - run:
          name: "Check Docker"
          command: docker version
