version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      resource_class: gpu.nvidia.small
      image: ubuntu-2004-cuda-11.6:2022.09.1
    steps:
      - checkout
      - run: lspci -k | grep -EA3 'VGA|3D|Display'
      - run:
          name: "Test if cuda is available.."
          command: nvidia-smi
      - run: docker version
      - run: dpkg -l nvidia-container-toolkit
      - run: nvcc --version
