workflows:
  version: 2
  main:
    jobs:
      - build


version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11-alpine
    steps:
      - checkout
      - run: |
          echo 'export TEST_VAR="chicken"' >> $BASH_ENV
          echo $TEST_VAR
      - run: |
          echo $TEST_VAR
