version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      #image: ubuntu-2004:202101-01
      image: ubuntu-1604:202104-01
    steps:
      - checkout
      - run: |
          echo $JAVA_HOME
          which javac
          which java
          go version
          jq --version
          docker --version
          #snapcraft --version
          node --version
          java -version
          nvm --version
          nvm install node
          node --version
