version: 2.1

orbs:
  brow: circleci/browser-tools@1.2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0-browsers
    steps:
      - brow/install-chrome
      - brow/install-chromedriver
      - run: |
          java --version
          google-chrome --version
