version: 2
jobs:
    build:
        docker:
            - image: docker:18.09.2-git
            - image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
              name: elasticsearch

        working_directory: ~/project
        steps:
            - checkout
            - setup_remote_docker:
                docker_layer_caching: true
            - run:
                name: Debug
                command: |
                  sleep 32
                  ps aux
                  sudo netstat -plntu
            - run:
                name: test
                command: |
                    docker run --rm \
                        --network host \
                        byrnedo/alpine-curl \
                        localhost:9200
