version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/android:api-30
    steps:
      - checkout
      - run: |
          echo $JAVA_HOME
          which javac
          which java
          jq --version
          docker --version
          java -version

          echo "======================================================="
          echo "======================================================="
          cat /opt/android/sdk/platform-tools/source.properties
