version: 2.1

orbs:
  ruby: circleci/ruby@1.0

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - ruby/install:
          version: "2.7.0"
      - run: ruby --version
