version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine: #true
      #image: ubuntu-2004:202201-02
      image: ubuntu-1604:202101-01
      #image: circleci/classic:201808-01
    steps:
      - run: |
          nvm install v14.0.1
          nvm alias default v14.0.1
          node --version
      - run: |
          node --version
