version: 2.0
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
      - image: circleci/postgres:10
    steps:
      - checkout
      - run:
          name: Debug
          command: |
            ps aux
            apt update && apt install net-tools
            sudo netstat -plntu
