version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run: |
          echo "=========================="
      - run:
          shell: /usr/local/bin/ruby
          command: puts "A string".inspect
