version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/golang:1.13
      - image: circleci/mysql:5.7
    steps:
      - checkout
      - run: |
          ls -lah ~/
          echo $PATH
