version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run: |
          docker --version
          docker-compose --version
          docker-compose up
