version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
        environment:
          TEST_VAR: chicken
          TEST_VAR2: pork
      - image: circleci/golang:1.9
        environment:
          - TEST_VAR4=goat
    environment:
      - TEST_VAR3: beef
    steps:
      - checkout
      - run:
          name: "Test Environment Values"
          command: echo $TEST_VAR; echo $TEST_VAR2; echo $TEST_VAR3
