version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/python:2.7
    steps:
      - checkout
      - run: |
          echo "Testing"
          python --version
          pip --version
          pip install linode-cli
