version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run:
          name: "Check Go Formatting"
          command: "! go fmt ./... 2>&1 | read"
