version: 2.1

orbs:
  irc: cci-orbs/irc@0.0.3

workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: cibuilds/base:2018.11
    steps:
      - checkout
      - run:
          name: "Testing Orbs"
          command: |
            echo "Hi"
      - irc/notify:
          server: "irc.freenode.net"
          channel: "testor"
