workflows:
  version: 2
  main:
    jobs:
      - build
      - deploy

version: 2
jobs:
  build:
    docker:
      - image: snapcore/snapcraft:edge
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Build Our Statically Generated Docs Website with Hugo"
          command: snapcraft --version
  deploy:
    docker:
      - image: cibuilds/hugo:0.34
    working_directory: ~/project
    steps:
      - run:
          name: "Deploy Our Docs Site"
          command: echo "This is where we'd deploy using rsync, awscli, etc."
