version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: "Testing"
          command: |
            echo "Hi"
            cat /etc/os-release
            sudo apt-get update
