version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-stretch-node-browsers
    steps:
      - checkout
      - run:
          name: "Do all the things!"
          command: |
            sudo apt-get update
