version: 2.1

parameters:
  hugo-version:
    type: string
    default: "0.1.0"

orbs:
  hugo: circleci/hugo@<< pipeline.parameters.hugo-version >>

workflows:
  main:
    jobs:
      - build:
          context: testing

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - run: |
          ls -lah ~/
          echo $PATH
      - run: |
          echo $SCOPE_CHECK
