version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: curl -sSL "https://github.com/WebAssembly/binaryen/releases/download/version_101/binaryen-version_101-x86_64-linux.tar.gz" | tar -xz -C /tmp/
      - run: echo 'export PATH=/tmp/binaryen-version_101/bin/wasm-opt:${PATH}' >> $BASH_ENV
      - run: wasm-opt
