version: 2.1

orbs:
  ruby: circleci/ruby@0.2.0

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/base:2019.11
    steps:
      - ruby/install:
          version: 2.7.0-preview1
      - run: |
          ruby --version
