version: 2.1
jobs:
  one:
    docker:
      - image: 'cimg/base:2020.05'
    steps:
      - run:
          command: echo "Hello"
  evaluate-master:
    docker:
      - image: 'cimg/base:2020.05'
    steps:
      - run:
          command: echo "World"
      - run:
          command: echo "Heal it"
workflows:
  version: 2
  build-and-test:
    jobs:
      - one
      - evaluate-master:
          requires:
            - one
          filters:
            branches:
              only: master


