version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Do all the things!"
          command: |
            ls -lah
            ls -lah /
            echo "================================"
            echo $SHELL
            echo $BASH_ENV
            ls -lah /var/lib/docker/
