version: 2.1

workflows:
  main:
    jobs:
      - build:
          context: testing

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - run: |
          ls -lah ~/
          echo $PATH
      - run: |
          echo $SCOPE_CHECK
