version: 2
jobs:
  node:
    working_directory: ~/some-app

    docker:
      - image: circleci/node:8.9

    steps:
      - checkout

      - restore_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: npm install

      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}-{{ arch }}
          paths:
            - ~/.cache/npm

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run:
          name: linters
          command: |
            npm run lint
            npm run flow

      - persist_to_workspace:
          root: ~/some-app
          paths:
            - node_modules

workflows:
  version: 2
  node-android-ios:
    jobs:
      - node
