version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run: |
          sudo apt-get update && sudo apt-get install postgresql-client
          # Test download Go with cURL
          curl -sSL "https://golang.org/dl/go1.14.4.linux-amd64.tar.gz" | sudo tar -xz -C /usr/local/
