version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: felicianotech/test:3
    steps:
      - checkout
      - run:
          name: "Do all the things!"
          command: |
            ps aux | grep -i Xvfb
            echo "====================================="
            cat /docker-entrypoint.sh
