version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      image: ubuntu-2004:2022.04.2
    steps:
      - checkout
      - run: dpkg --print-architecture
      - run:
          name: "Check Envars"
          command: |
            sudo echo $DEBIAN_FRONTEND
            echo $JAVA_HOME
            ls -lah ~/.nvm
      - run: |
          cat /etc/passwd
          cat /etc/group
      - run:
          name: "OpenVPN systemd test"
          command: |
            sudo apt-get update
            sudo apt-get install -y openvpn-systemd-resolved
      - run: |
          cat /etc/apt/sources.list
          which javac
          which java
          go version
          jq --version
          docker --version
          #snapcraft --version
          node --version
          java -version
          nvm --version
          nvm install node
          node --version
          cat /etc/os-release
          sudo apt-get update
