version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: cimg/python:3.8-node
    steps:
      - run: python --version
      - run: pip install awscli
      - run: aws --version
