version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/python:3.5
    steps:
      - checkout
      - run: |
          echo "Testing"
          pip install linode-cli
