version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run: |
          python --version
          python3 --version
          pyenv --version
          pyenv install -s 3.8.5
          pyenv global 3.8.5
          python --version
          python3 --version
