version: 2.1

parameters:
  via-api:
    type: string
    default: ""

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - run: |
          ls -lah ~/
          echo $PATH
      - run: |
          echo << pipeline.parameters.via-api >>
