version: 2.1

workflows:
  main:
    jobs:
      - build-april
      - build-june

jobs:
  build-april:
    machine:
      image: android:2022.04.1
    #resource_class: arm.medium
    steps:
      - run: echo "hi"
  build-june:
    machine:
      image: android:2022.06.1
    #resource_class: arm.medium
    steps:
      - run: echo "hi"
