version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:9.4.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Start container and verify it's working
          command: |
            sudo docker-compose up --build
