version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      image: ubuntu-1604:canary
    steps:
      - checkout
      - run: |
          sudo apt-get update && sudo apt-get install postgresql-client
          ls -lah /etc/apt/sources.list.d/
          sudo apt update
