version: 2.1

workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: cimg/node:1.16
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6
      - run:
          name: "Do all the things!"
          command: |
            docker version
