version: 2.1

orbs:
  hugo: circleci/hugo:0.3.0

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    macos:
      xcode: "9.4.1"
    steps:
      - run:
          command: echo "Hello World!!"
      - hugo/install
      - run: hugo version
      - run: hugo new site
