version: 2.1

orbs:
  theorb: circleci/rememborb@0.0.1

workflows:
  main:
    jobs:
      - build
      - build2:
          requires:
            - build

jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - run: apk add -U git tar bash
      - theorb/remember:
          env_var: TEST_VAR
          value: 'HappyBirthday'
      - run: |
          echo $TEST_VAR
  build2:
    docker:
      - image: alpine:3.7
    steps:
      - run: apk add -U git tar bash
      - theorb/recall:
          env_var: TEST_VAR
      - run: |
          echo ${TEST_VAR}
