version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      image: ubuntu-2004:current
      #image: ubuntu-2004:202201-02
      #image: ubuntu-1604:202101-01
      #image: circleci/classic:201808-01
    environment:
      NVM_DIR: "chicken"
      TESTOR: "turk"
    steps:
      - run: |
          echo $SSH_CONFIG_DIR
          python3 --version
          pip3 install requests
      - run: gcloud --version
      - run: snap list
      - run: echo $NVM_DIR
      - run: echo $TESTOR
      - run: cat ~/.bashrc
      - run: uname -a
      - run: docker buildx
