version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.6
    steps:
      - checkout
      - run: |
          node --version
          npm --version
          sudo npm update -g
          npm update
          sudo npm install npm -g
          npm --version
