version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run:
          name: "Check Envar"
          command: |
            TESTING3=$( echo $CIRCLE_WORKING_DIRECTORY )"/test-dir"
            echo $TESTING3
            mkdir -p $CIRCLE_WORKING_DIRECTORY/foo/bar
            ls -lah
