version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: cimg/node:16.0
        environment:
          POSTGRES_USER: root
      - image: circleci/postgres:13.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: Apple
    steps:
      - checkout
      - run:
          name: "Do all the things!"
          command: |
            sudo apt-get update && sudo apt-get install -y postgresql-client
            sleep 1
            psql postgresql://root:Apple@127.0.0.1:5432/?sslmode=disable
