version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.6
    steps:
      - checkout
      - run: |
          node --version
          npm --version
          sudo npm install npmlog -g
          npm install npm@latest -g
          npm --version
