version: 2.1

workflows:
  main:
    jobs:
      - build:
        environment:
          MY_CUSTOM_VAR: "bye"

jobs:
  build:
    docker:
      - image: cibuilds/base
    steps:
      - run: echo "Hi"
      - run: echo $MY_CUSTOM_VAR
