version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
      - image: cimg/mariadb:10.1
    steps:
      - run: sudo apt-get update && sudo apt-get install -y mariadb-client
      # Then test with SSH
