workflows:
  version: 2
  main:
    jobs:
      - build


version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: mkdir $HOME/test-dir; touch $HOME/test-dir/file.txt; ls -lah $HOME; ls -lah; pwd
      - persist_to_workspace:
          root: $HOME
          paths:
            - test-dir
