version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Check variable"
          command: uname -a
      - run:
          name: "See Python versions"
          command: |
            dpkg -l | grep python
