version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run: |
          echo "export PATH=$PATH:/snap/bin" >> $BASH_ENV
          source /etc/environment
      - run: |
          sudo snap install sonar
          sudo snap install gotham
      - run: |
          ls -lah /snap/bin
          cat $BASH_ENV
          uname -a
          sonar version
          gotham version
