version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          docker --version
          docker-compose --version
          cat /etc/-os-release
          uname -a
