version: 2.1

orbs:
    python: circleci/python@0.1.0

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    #machine: true
    steps:
      - python/install
      - run: |
          python --version
          pip --version
