version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: cimg/go:1.13
    steps:
      - checkout
      - run:
          name: "Do all the things!"
          command: |
            echo $SHELL
