version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.4
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run: echo $SSH_CONFIG_DIR
      - run: |
          echo "=========================="
