version: 2.1

workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: cibuilds/base:2018.11
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.0-ce
      - run:
          name: "Testing Orbs"
          command: |
            echo "Hi"
