version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: "Testing"
          command: |
            echo "Hi"
            cat /etc/os-release
            sudo apt-get update
