version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: cimg/go:1.14.4
    steps:
      - checkout
      - run:
          name: "Do all the things!!"
          command: |
            python3 --version
            python --version
