version: 2
jobs:
  build:
    docker:
      - image: williamyeh/ansible:ubuntu16.04
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: Debug
          command: |
            pwd
            ls -lah ~/.ssh/
