version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/base:stable
      - image: circleci/postgres:9.6.17
        environment:
          POSTGRES_USER: turkey
          POSTGRES_PASSWORD: chicken9
    steps:
      - checkout
      - run: |
          sudo apt-get update && sudo apt-get install postgresql-client
