version: 2
jobs:
  build:
    docker:
      - image: golang:1.8-alpine
    working_directory: /go/src/github.com/myorg/myproject
    steps:
      - checkout: {}
      - run:
          name: "Check Docker"
          command: echo "Hi"
      - run:
          name: "Check Docker"
          command: echo "Hey"
