version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      #- image: cimg/base:current
      - image: felicianotech/test:git
    working_directory: /mnt/ramdisk
    steps:
      - run: git --version
      - run: git config --global --add safe.directory '*'
      - run: git config --global --get safe.directory
      - checkout
      - run: echo 'TESTOR=chicken' >> ~/.bashrc
      - run: node --version
      - setup_remote_docker:
          version: 20.10.14
      - run: docker --version | cut -d' ' -f3 | cut -d',' -f1
      - run: lsb_release -cs
      - run: |
          echo "=========================="
