version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run: echo 'TESTOR=chicken' >> ~/.bashrc
      - run: echo $TESTOR
      - setup_remote_docker:
          version: 20.10.14
      - run: docker --version | cut -d' ' -f3 | cut -d',' -f1
      - run: lsb_release -cs
      - run: |
          echo "=========================="
