version: 2.1

orbs:
    python: circleci/python@0.1.9

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    executor: python/default
    steps:
      - run: |
          python --version
          pip --version
      - run: echo "Django==1.3" > requirements.txt
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run: ls -lah ~/.local/lib/
