version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      image: android:2021.10.1
    #resource_class: arm.medium
    steps:
      - checkout
      - run: |
          echo $JAVA_HOME
          which javac
          which java
          jq --version
          docker --version
          node --version
          java -version
          gcloud --version
          echo "Hi"
          sdkmanager --install "ndk;21.3.6528147"
