version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/python:3.8-node
      - image: circleci/postgres:9.6.17
        environment:
          POSTGRES_USER: turkey
          POSTGRES_PASSWORD: chicken9
    steps:
      - checkout
      - run: |
          # Exit on purpose.
          exit 0
      - run: |
          echo "Hi, does this still run?"
