version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: cimg/node:16.0
        environment:
          POSTGRES_USER: root
          PGDATABASE: circle_test
      - image: felicianotech/postgres:dev3
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: Apple
    steps:
      - checkout
      - run:
          name: "Do all the things!"
          command: |
            sudo apt-get update && sudo apt-get install -y postgresql-client
            sleep 1
            #cat test.sql | psql postgresql://root:Apple@127.0.0.1:5432/circle_test?sslmode=disable
            #PGPASSWORD=Apple psql -h localhost -p 5432 -U root -c "\l"
            PGPASSWORD=Apple pg_isready -h localhost -p 5432 -U root
