version: 2
jobs:
  build:
    docker:
      - image: felicianotech/test:michele-so3
    steps:
      - checkout
      - run:
          name: "Check Docker"
          command: |
            if [[ ! $CIRCLE_JOB ]]; then
              echo "CIRCLE_JOB is not set"
            else
              echo "CIRCLE_JOB is set"
              echo "And the value is: " $CIRCLE_JOB
            fi
