version: 2.1

orbs:
  hugo: felicianotech/hugo@0.0.2

workflows:
  main:
    jobs:
      - build
jobs:
  build:
    executor: hugo/hugo-image
    steps:
      - checkout
      - run:
          name: "Testing Orbs"
          command: |
            echo "Hi"
      - run:
          name: "Testing Orbs"
          command: |
            hugo version
