version: 2
jobs:
  build:
    machine: true
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Check variable"
          command: echo $BASH_ENV
      - run:
          name: "See Python versions"
          command: |
            dpkg -l | grep python
