version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.12
      - run: docker --version
      - run: lsb_release -cs
      - run: |
          echo "=========================="
