version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run:
          name: "Run Script That Should Fail in 30 seconds"
          command: ./fail.sh &
      - run: sleep 300
      - run:
          name: "This should never run."
          command: echo "Damn, I ran."
