version: 2.1

orbs:
  bt: circleci/browser-tools@1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    macos:
      xcode: "13.0.0"
    steps:
      - run: ls -lah /usr/local/bin
      - bt/install-chrome
      - run: cat /usr/local/bin/google-chrome
