version: 2.0
workflows:
  version: 2
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run:
          name: "Let's test things!!"
          command: |
            circleci version
