version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run: |
          sudo apt-get update && sudo apt-get install postgresql-client
          sudo apt update
