version: 2
jobs:
  build:
    docker:
      - image: naftulikay/circleci-lambda-rust:latest
        environment:
          TEST_VAR: chicken
          TEST_VAR2: pork
    environment:
      - TEST_VAR3: beef
    steps:
      - checkout
      - run:
          name: "Test Environment Values"
          command: echo $TEST_VAR; echo $TEST_VAR2; echo $TEST_VAR3
