version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: cimg/base:2022.09
    steps:
      - run: curl -sSL google.com
      - run: sudo apt-get update && sudo apt-get install -y dnsutils
      - run: dig A circleci.com
      - run : cat /etc/passwd
