version: 2.1

workflows:
  main:
    jobs:
      - ubuntu-default
      - ubuntu-1404
      - ubuntu-1604

jobs:
  ubuntu-default:
    machine: true
    steps:
      - run: echo "I ran successfully"
      - run: cat /etc/os-release
  ubuntu-1404:
    machine:
      image: circleci/classic:201808-01
    steps:
      - run: echo "I ran successfully"
  ubuntu-1604:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - run: echo "I ran successfully"
