version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      image: windows-server-2019-vs2019:stable
      resource_class: windows.medium
    steps:
      - checkout
      - run: |
          ssh -V
          putty --version
          node --version
          go version
          npm list
          npx eslint --version
          npm list
