version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/base:2021.04
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run: |
          echo "hi"
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          psql -U postgres -c "\l"
