version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      image: ubuntu-2004:202111-02
      #image: ubuntu-1604:202101-01
      #image: circleci/classic:201808-01
    steps:
      - run: echo $NVM_DIR
      - run: uname -a
      - run: docker buildx
