version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: "Do all the things!!"
          command: |
            docker version
            docker build -t my-org/my-image .
            docker push my-org/my-image
