version: 2
jobs:
  build:
    machine: true
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "See Docker Version"
          command: docker --version
      - run:
          name: "See Python versions"
          command: |
            dpkg -l | grep python
