version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/base:2021.07
        environment:
          POSTGRES_USER: postgres
      - image: circleci/postgres:12.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run: |
          echo "=== 1 ====================="
          sudo apt-get update && sudo apt-get install -y postgresql-client
          echo "=== 2 ====================="
          echo 'CREATE DATABASE testdb' | psql
          echo "=== 3 ====================="
