version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      image: windows-server-2022-gui:2022.06.1
      #image: windows-server-2019-nvidia:stable
      resource_class: windows.medium
      #resource_class: windows.gpu.nvidia.medium
    steps:
      - checkout
      - run: |
          python --version
          python2 --version
          ssh -V
          node --version
          go version
          npm list
          npx eslint --version
          npm list
