version: 2
jobs:
  build:
    docker:
      - image: circleci/mysql:5.7.22-ram
    steps:
      - checkout
      - run:
          name: "Test"
          command: |
            free -m
            cat /var/log/mysql
