workflows:
  version: 2
  main:
    jobs:
      - build


version: 2
jobs:
  build:
    docker:
      - image: alpine:3.8
    steps:
      - checkout
      - run: |
          echo 'export TEST_VAR="chicken"' >> $BASH_ENV
          echo $TEST_VAR
      - run: |
          echo $TEST_VAR
