version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      #image: ubuntu-2204:current
      image: ubuntu-2204:2022.04.2
      #image: ubuntu-2004:current
      #image: ubuntu-2004:2022.04.1
      #image: ubuntu-1604:202101-01
      #image: circleci/classic:201808-01
    environment:
      NVM_DIR: "chicken"
      TESTOR: "rednytiger"
    steps:
      - run: curl https://cli-assets.heroku.com/apt/release.key | sudo apt-key add -
      - run: sudo apt-get update
      - run: echo $TESTOR
      - run: docker compose --version
      - run: cat /etc/apt/sources.list
      - run: |
          echo $SSH_CONFIG_DIR
          python3 --version
          pip3 install requests
      - run: gcloud --version
      - run: snap list
      - run: echo $NVM_DIR
      - run: cat ~/.bashrc
      - run: cat $BASH_ENV
      - run: uname -a
