version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run:
          name: "Check Version"
          command: "node --version"
      - save_cache:
          key: test-{{ arch }}
          paths:
            - "main.go"

workflows:
  version: 2
  normal:
    jobs:
      - build
  hourly-workflow-2:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only: temp/2.0-docker
    jobs:
      - build
