version: 2.1

orbs:
    go: circleci/go@0.1.0

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/python:3
    #machine: true
    steps:
      - go/install
      - run: go version
