version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      image: ubuntu-1604-cuda-10.1:201909-23
    steps:
      - checkout
      - run:
          name: "Test is cuda is available."
          command: nvidia-smi
