version: 2.0
workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - tag-only:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
    steps:
      - checkout
      - run:
          name: "Let's tag things!!"
          command: |
            if [ -z "$CIRCLE_TAG" ]; then
              git tag v1
              git push -u origin v1
            fi
  tag-only:
    docker:
      - image: circleci/golang:1.12
    steps:
      - run: "This only runs on tags."
