version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      resource_class: gpu.nvidia.small
      image: ubuntu-1604-cuda-11.1:202012-01
    steps:
      - checkout
      - run:
          name: "Test is cuda is available.."
          command: nvidia-smi
      - run: docker version
