version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      image: ubuntu-1604:202010-1
    steps:
      - checkout
      - run: |
          docker --version
          docker-compose --version
