version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run: |
          echo "export PATH=$PATH:/snap/bin" >> $BASH_ENV
          echo "/etc/profile.d/apps-bin-path.sh" >> $BASH_ENV
      - run: |
          sudo snap install sonar
      - run: |
          ls -lah /snap/bin
          cat $BASH_ENV
          snap run sonar version
          /snap/bin/sonar version
