version: 2
jobs:
  build:
    docker:
      - image: go:1.8
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Check variable"
          command: echo $BASH_ENV
      - run:
          name: "See Python versions"
          command: |
            dpkg -l | grep python
