version: 2
jobs:
  build:
    machine: true
    working_directory: ~/project
    environment:
      - DEBIAN_FRONTEND: "noninteractive"
    steps:
      - checkout
      - run:
          name: "Install Vagrant and spit up VM."
          command: |
            uname -a
            docker --version
            docker run ubuntu:16.04 uname -a
