version: 2.1

orbs:
    gcp: circleci/gcp-cli@volatile

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - gcp/install
      - run: gcloud version
