version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.0-browsers
    steps:
      - checkout
      - run:
          name: "Check Docker"
          command: |
            if [ -z ${CIRCLE_JOB+x} ]; then
              echo "CIRCLE_JOB is not set"
            else
              echo "CIRCLE_JOB is set"
            fi
