version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.6
    steps:
      - checkout
      - run: |
          node --version
          npm --version
          sudo rm -rf /usr/local/lib/node_modules/
          sudo npm install npm@latest -g
          npm --version
