version: 2.1

orbs:
    php: circleci/php@0.1.0

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/python:3
    #machine: true
    steps:
      - php/install
      - run: php -v
      - php/install-composer
      - run: composer --version
