version: 2.1

orbs:
  s3: circleci/aws-s3@1.1.0

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/go:1.14.1
    steps:
      - s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: bucket
          to: 's3://my-s3-bucket-name/prefix'
