version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run: |
          echo "PATH=$PATH:/snap/bin" >> $BASH_ENV
      - run: |
          sudo snap install gotham
          ls -lah /snap/bin
          cat $BASH_ENV
          gotham version
