version: 2.0
workflows:
  version: 2
  main:
    jobs:
      - build:
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch
    steps:
      - checkout
      - run:
          name: "Let's test things!!"
          command: sudo apt-get update
