version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      #image: ubuntu-2004:202008-01
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run: |
          echo "export PATH=$PATH:/snap/bin" >> $BASH_ENV
      - run: |
          sudo snap install sonar
      - run: |
          echo $PATH
          snap run sonar version
          sonar version
