version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: felicianotech/test:dev-node
    steps:
      - checkout
      - run: cat ~/.circlerc
      - run: cat ~/.bashrc
      - run: cat ~/.profile
      - run: echo $SHELL
      - run: echo $TESTOR
      - run: node --version
      - setup_remote_docker:
          version: 20.10.14
