version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      #image: ubuntu-2004:202111-02
      image: circleci/classic:201808-01
    steps:
      - run: ssh -V
      - run: uname -a
