version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      image: ubuntu-2204:2022.07.1
    steps:
      - checkout
      - run:
          name: "Update Apt Index"
          command: sudo apt-get update && sudo apt-get upgrade
      - run: dpkg --print-architecture
      - run: sudo apt-get update && sudo apt-get install -y openvpn openvpn-systemd-resolved
      - run:
          name: "Check Envars"
          command: |
            echo $DEBIAN_FRONTEND
            echo $JAVA_HOME
      - run:
          name: "Check Versions"
          command: |
            dpkg -l | grep " openssl "
      - run: |
          cat /etc/passwd
          cat /etc/group
          ls -lah ~/ | grep -i ssh
      - run:
          name: "OpenVPN systemd test"
          command: |
            sudo apt-get update
            sudo apt-get install -y openvpn-systemd-resolved
      - run: |
          cat /etc/apt/sources.list
          which javac
          which java
          go version
          jq --version
          docker --version
          #snapcraft --version
          node --version
          java -version
          nvm --version
          nvm install node
          node --version
          cat /etc/os-release
          sudo apt-get update
