version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      image: ubuntu-2004:canary
    steps:
      - checkout
      - run: |
          sudo snap install sonar
      - run: |
          snap run sonar version
          sonar version
