version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Do all the things!!"
          command: |
            sudo groupadd bumpty
            sudo usermod -aG bumpty $USER
            groups
            newgrp bumpty
            groups
      - run:
          name: "Do all the things!!"
          command: |
            groups
