version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run:
          name: "Check Envars"
          command: |
            echo $CIRCLE_PULL_REQUEST
            echo "---------------------------------------------"
            echo $CIRCLE_PULL_REQUESTS
