version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: cimg/base:2022.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.12
      - run: docker version
      - run: |
          echo "=========================="
