version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      #image: ubuntu-1604:canary
      #image: ubuntu-2004:202010-01 
      #image: ubuntu-2004:202101-01
      image: ubuntu-1604:202101-01
    #resource_class: arm.medium
    steps:
      - checkout
      - run: |
          go version
          jq --version
          docker --version
          #snapcraft --version
          node --version
          java -version
