version: 2.1

orbs:
  hugo: felicianotech/hugo@0.0.4

workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: cibuilds/base
    steps:
      - checkout
      - run:
          name: "Testing Orbs"
          command: |
            echo "Hi"
      - hugo/install:
          version: "0.50"
      - run:
          name: "Testing Orbs"
          command: |
            hugo version
