version: 2.1

orbs:
  hugo: felicianotech/hugo@0.0.3

workflows:
  main:
    jobs:
      - build
jobs:
  build:
    executor:
      name: hugo/image
      version: "0.49"
    steps:
      - checkout
      - run:
          name: "Testing Orbs"
          command: |
            echo "Hi"
      - run:
          name: "Testing Orbs"
          command: |
            hugo version
