version: 2.1

orbs:
  hugo: circleci/hugo@0.5
  jq: circleci/jq@2.0

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    executor:
      name: hugo/cibuilds
    environment:
      WORD: Hi
    steps:
      - run: echo $WORD
