version: 2.0
workflows:
  version: 2
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
      - image: ccistaging/mongo:4.1-bionic
    steps:
      - checkout
      - run:
          name: "Let's test things!!"
          command: sudo apt-get update
