version: 2.1

orbs:
  hugo: circleci/hugo@dev:ricardo-test
  jq: circleci/jq@2.0

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt-get update && apt-get install -y curl
      - hugo/install:
          version: "0.69.2"
      - run: hugo version
      - run: apt-get update && apt-get install -y jq
      - jq/install
      - run: jq --version
