version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      image: android:202102-01
      #image: android:canary
    #resource_class: arm.medium
    steps:
      - checkout
      - run: |
          echo $JAVA_HOME
          which javac
          which java
          jq --version
          docker --version
          node --version
          java -version
          gcloud --version
