version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run:
          name: "Check Envar"
          command: |
            echo $CIRCLE_WORKING_DIRECTORY
            TESTING=${CIRCLE_WORKING_DIRECTORY}"/test-dir"
            echo $TESTING
            TESTING3=$( echo $CIRCLE_WORKING_DIRECTORY )"/test-dir"
            echo $TESTING3
