version: 2.1

workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: cibuilds/base
    steps:
      - checkout
      - run:
          command: |
            git submodule update --recursive --init
