version: 2
jobs:
  build:
    docker:
      - image: williamyeh/ansible:ubuntu16.04
    steps:
      - checkout
      - run:
          name: Debug
          command: |
            pwd
            ls -lah
