version: 2.0
workflows:
  version: 2
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
      - image: circleci/postgres:10
    steps:
      - checkout
      - run:
          name: "Let's test things!!"
          command: |
            sudo apt update && sudo apt install -f postgresql-client net-tools
            sudo netstat -plntu
            psql -U postgres -c '\l'
