version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.6
    steps:
      - checkout
      - run: |
          node --version
          npm --version
          which npm
          sudo rm -rf /usr/local/lib/node_modules/
          #curl -L https://www.npmjs.org/install.sh | sudo sh
          #npm --version
          sudo npm cache clean --force
          sudo npm install npm@latest -g
          npm --version
