version: 2.0
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
      - image: circleci/postgres:10
        environment:
          PGPORT: 5555
    steps:
      - checkout
      - run:
          name: Debug
          command: |
            sleep 32
            ps aux
            sudo netstat -plntu
