version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: |
          echo "Testing"
          echo -e '\E[33m'Congratulations!'\E[0m'
