version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.3

workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: "Saying Hi"
          command: |
            echo "Hi"
      - cli/install
      - run: circleci diagnostic
