version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
      - image: redis:2.8
    steps:
      - checkout
      - run: |
          echo "Hi!!!!"
