version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: mkdir $HOME/test-dir; touch ./test-dir/file.txt
      - persist_to_workspace:
          root: .
          paths:
            - $HOME/test-dir
