version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine: true
    steps:
      - run: |
          ssh -v localhost
          sudo apt-get update && sudo apt-get -y dist-upgrade
          ssh -v localhost
      - run: python --version
      - run: python3 --version
      - run: which python
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y cowsay
      - run: |
          ssh -v localhost
          echo $JAVA_HOME
          which javac
          which java
          aws --version
          yq --version
          go version
          jq --version
          docker --version
          node --version
          echo "npm version:"
          npm --version
          java -version
          cat /etc/os-release
          sudo apt-get update
          systemctl --version
